title: "Smoke 'n' Seoul"
email: GREG@SMOKENSEOUL.COM
description: "KC BBQ + Korean. We're not your traditional BBQ restaurant but we have worked hard to make sure our meat stands up to the high standards that have been set here in Kansas City."
baseurl: ""
url: "http://www.smokenseoul.com"
twitter_username: smokenseoul
github_username: smokenseoul

theme: minima
plugins:
  - jekyll-feed
